apiVersion: v1
kind: Service
metadata:
  name: fleet-maintenance-bff
  namespace: fleet-maintenance
  labels:
    app: fleet-maintenance-bff
    app.kubernetes.io/part-of: fleet-maintenance
spec:
  selector:
    app: fleet-maintenance-bff
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
